version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASS=lamaya
      - DB_NAME=fastapi
      - DB_USER=postgres
      - SECRET_KEY=75719256c3e462bcfd5682534ff9c413e5c9b804ffe1b03fff73b818d00f2667
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lamaya
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
