"""initial-tables

Revision ID: 07b777ca71a5
Revises: 0706274c6bdf
Create Date: 2022-08-06 07:05:24.325965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b777ca71a5'
down_revision = '0706274c6bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
